# Introducción a NumPy

_Hasta ahora hemos visto los tipos de datos más básicos que nos ofrece Python: integer, real, complex, boolean, list, tuple...  Pero nos faltan los arreglos o vectores, en Pyhton son los  __arrays__._

_En esta parte, nos introduciremos en el paquete __NumPy__ y aprenderemos a crear arrays y a operar con ellos_.

## ¿Qué es un array?

Un array es un __bloque de memoria que contiene elementos del mismo tipo__. Básicamente:

* nos _recuerdan_ a los vectores, matrices, tensores...
* podemos almacenar el array con un nombre y acceder a sus __elementos__ mediante sus __índices__.
* ayudan a gestionar de manera eficiente la memoria y a acelerar los cálculos.


---

| Índice     | 0     | 1     | 2     | 3     | ...   | n-1   | n  |
| ---------- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Valor      | 2.1   | 3.6   | 7.8   | 1.5   | ...   | 5.4   | 6.3 |

---

__¿Qué podemos guardar en arrays?__

* Vectores y matrices.
* Datos de experimentos:
    - En distintos instantes discretos.
    - En distintos puntos del espacio.
* Resultado de evaluar funciones con los datos anteriores.
* Discretizaciones para usar algoritmos de: integración, derivación, interpolación...
* ...

## NumPy

NumPy es un paquete fundamental para la programación científica que __proporciona un objeto tipo array__ para almacenar datos de forma eficiente y una serie de __funciones__ para operar y manipular esos datos.

Para usar NumPy lo primero que debemos hacer es importarlo:

In [ ]:
import numpy as np
#para ver la versión que tenemos instalada:
np.__version__
# es usual y recomendable, y todos los hace, importar a numpy con el alias "np"

'1.21.2'

## Apliquemos NumPy

Vamos a __crear nuestros primeros arrays__:

Los arrays de una dimensión se crean pasándole __una lista__ como argumento a la función `np.array`.

In [ ]:
# Array de una dimensión
primer_array = np.array([1, 2, 3, 4])
primer_array

array([1, 2, 3, 4])

In [ ]:
# Podemos usar print
print(primer_array)

[1 2 3 4]


In [ ]:
# Podemos comprobar el tipo de primer_array
type(primer_array)

numpy.ndarray

In [ ]:
# Podemos comprobar el tipo de datos que contiene
primer_array.dtype

dtype('int64')

Para crear un array de dos dimensiones le pasaremos una _lista de listas_:

In [ ]:
# Array de dos dimensiones
segundo_array = np.array([[1, 2, 3], [4, 5, 6]])
print(segundo_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Array de dos dimensiones
tercer_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(tercer_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<div class="alert alert-info">Podemos continuar en la siguiente línea usando `\`, pero no es necesario escribirlo dentro de paréntesis o corchetes</div>

Esto sería una buena manera de definirlo, de acuerdo con el [PEP 8 (indentation)](http://legacy.python.org/dev/peps/pep-0008/#indentation):

In [ ]:
cuarto_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [ ]:
print(cuarto_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Funciones y constantes de NumPy

NumPy también incorporá __funciones__. Veamos un ejemplo sencillo:

In [ ]:
# Suma
np.sum(primer_array)

10

In [ ]:
# Máximo
np.max(primer_array)

4

In [ ]:
# Mínimo
np.min(primer_array)

1

In [ ]:
np.average(primer_array)

2.5

In [ ]:
n, m = tercer_array.shape
print(n,m)

3 3


#### Vectorización
Este es un aspecto muy interesante que tiene incluido Python, similar a otros lenguajes de alto nivel.

In [ ]:
# Seno
seno_primr_array = np.sin(segundo_array)
print(seno_primr_array)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


Además de algunas __constantes__ que pueden sernos útiles:

In [ ]:
np.pi, np.e

(3.141592653589793, 2.718281828459045)

## Funciones para crear arrays

Hemos visto que la función `np.array()` nos permite crear arrays con los valores que nosotros introduzcamos manualmente a través de listas.
Más adelante, aprenderemos a leer ficheros y almacenarlos en arrays.
Mientras tanto, ¿qué puede hacernos falta?

#### Array de ceros
En caso que necesitemos un vector lleno de ceros ...

In [ ]:
# En una dimensión, creamos un arreglo de largo 100, lleno de ceros
cero = np.zeros(100, complex)
print(cero)

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [ ]:
# Observen la diferencia
ceros = np.zeros([100], complex)
print(ceros)

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [ ]:
# En dos dimensiones, ídem ...
cero2D = np.zeros([5, 4, 3])
print(cero2D)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


<div class="alert alert-info"><strong>Nota:</strong>
En el caso 1D es válido tanto `np.zeros([5])` como `np.zeros(5)` (sin los corchetes), pero no lo será para el caso nD
</div>

#### Array "vacío"
supongamos que necesitamos un vector vacío

In [ ]:
array_vacio = np.empty(10)
print(array_vacio)

[4.64985807e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 6.90157911e-310 8.82931459e+169 1.38053643e-047 5.49510908e-090
 2.51563945e+180 4.65082078e-310]


<div class="alert alert-warning"><strong>Importante:</strong>
El array vacío se crea en un tiempo algo inferior al array de ceros. Sin embargo, el valor de sus elementos será arbitrario y dependerá del estado de la memoria. Cuandpo lo utilicemos debemos asegurarnos de que se llenen bien todos sus elementos, pues seguramente introducirá resultados erróneos.
</div>

#### Array de unos
Vamos a crear un vector lleno de unos.
Observemos que crearemos 3 filas y 2 columnas.

In [ ]:
unos = np.ones([3, 2])
print(unos)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


<div class="alert alert-info"><strong>Nota:</strong>
Otras funciones muy útiles son `np.zeros_like` y `np.ones_like`. Usa la ayuda para ver lo que hacen si lo necesitas.
</div>

In [ ]:
# help(np.zeros_like)

In [ ]:
print(cuarto_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
quinto_array = np.zeros_like(cuarto_array)
print(quinto_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
y = np.arange(3, dtype=float)
print(y)

[0. 1. 2.]


In [ ]:
y = np.arange(8, 13, dtype=complex)
print(y)

[ 8.+0.j  9.+0.j 10.+0.j 11.+0.j 12.+0.j]


In [ ]:
simil_ceros = np.zeros_like(y)
print(simil_ceros)

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [ ]:
simil = np.zeros_like(y)
simil_unos = np.ones_like(y)
print(simil)
print(simil_unos)

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]


#### Array identidad
Una Matriz identidad, siempre debe ser cuadrada, por lo que sólo es necesario indicar una dimensión.

In [ ]:
A = np.identity(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<div class="alert alert-info"><strong>Nota:</strong>
También puedes probar `np.eye()` y `np.diag()`.
</div>

In [ ]:
help(np.eye)

In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
np.eye(5, dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.eye(4, dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [ ]:
np.eye(4, k = -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
help(np.diag)

In [ ]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(a)
b = np.diag(a)
print(b)
c = np.diag(a, k=-1)
print(c)
d = np.diag(a, k=2)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[3 7]
[2]


### Rangos
Veamos como hacer arreglos de un determinado rango

#### np.arange

NumPy, definamos __un array que vaya de 2 a 7__:

In [ ]:
a = np.arange(2, 7)
a

array([2, 3, 4, 5, 6])

__Observa con atención el resultado anterior__
Hay algo que deberías grabar para simpre?
__El último elemento no es 7 sino 6__

NumPy, hagamos __un array que vaya de 0 a 10, de 3 en 3__:

In [ ]:
s = np.arange(0, 15, 4)
print(s)

[ 0  4  8 12]


#### np.linspace

El que ha usado `MATLAB` alguna vez, seguro que esto le parece conocido:

In [ ]:
# Definamos una variable, por ejemplo x, desde 0 hasta 10, con un total de 21 pasos
x = np.linspace(0, 10, 11)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


En este caso sí que se incluye el último elemento.

<div class="alert alert-info"><strong>Nota:</strong>
También puedes probar `np.logspace()`
</div>

In [ ]:
y = np.logspace(0, 10, 11)
print(y)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10]


### reshape
Supongamos que tenemos un vector con datos y queremos darle el formato de una matriz.

Con `np.arange()` es posible crear "vectores" cuyos elementos tomen valores consecutivos o equiespaciados, como hemos visto anteriormente. ¿Podemos hacer lo mismo con "matrices"? Pues no, pero sí.
Imaginemos que queremos crear algo como esto:

\begin{pmatrix}
    1 & 2 & 3\\
    4 & 5 & 6\\
    7 & 8 & 9\\
    \end{pmatrix}

* Comenzaremos por crear un array 1d con los valores $(1,2,3,4,5,6,7,8,9)$ usando `np.arange()`.
* Luego le daremos forma de array 2d. con `np.reshape(array, (dim0, dim1))`.
Esto es:

In [ ]:
a = np.arange(1, 13)
print(a)
M = np.reshape(a, [2, 6])
M

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# También funciona como método
N = a.reshape([2,6])
N

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

<div class="alert alert-info"><strong>Nota:</strong>
No vamos a entrar demasiado en qué son los métodos, pero debes saber que están asociados a la programación orientada a objetos y que en Python todo es un objeto. Lo que debes pensar es que son unas funciones especiales en las que el argumento más importante (sobre el que se realiza la acción) se escribe delante seguido de un punto. Por ejemplo: `<objeto>.método(argumentos)`
</div>

<div class="alert alert-success"><strong>Nota:</strong>
¿Vieron que bonita la matriz?
 Esto se puede lograr, gracias a que en Markdown, podemos utilizar <b><em>LaTex</em></b> para escribir, por ejemplo, ecuaciones.
</div>

   $$ x_i = \log\left[{\frac{y^{2 . z}}{5-\sin\left(\theta \cdot \sqrt{\Phi}\right)}}\right] $$

## Operaciones

### Operaciones elemento a elemento

Ahora que sabemos varias cosas de los arrays, hagamos algunas operaciones.
El funcionamiento es el habitual en _FORTRAN_ y _MATLAB_ y poco hay que añadir:

In [ ]:
#crear un array y sumarle un número
arr = np.arange(11)
print('arr =', arr)
print(arr + 55)

arr = [ 0  1  2  3  4  5  6  7  8  9 10]
[55 56 57 58 59 60 61 62 63 64 65]


In [ ]:
#multiplicarlo por un número
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#elevarlo al cuadrado
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
#calcular una función
np.tanh(arr)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997,
       1.        ])

<div class="alert alert-info"><strong>Entrenamiento:</strong>
Puedes tratar de comparar la diferencia de tiempo entre realizar la operación en bloque, como ahora, y realizarla elemento a elemento, recorriendo el array con un bucle.
</div>

In [ ]:
#medir el tiempo utilizado para calcular la función
%time np.tanh(arr)

CPU times: user 43 µs, sys: 4 µs, total: 47 µs
Wall time: 52.7 µs


array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997,
       1.        ])

__Si las operaciones involucran dos arrays también se realizan elemento a elemento__

In [ ]:
#creamos dos arrays
arr1 = np.arange(0, 11)
arr2 = np.arange(20, 31)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[20 21 22 23 24 25 26 27 28 29 30]


In [ ]:
#los sumamos
arr1 + arr2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
#multiplicamos
arr1 * arr2

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

#### Comparaciones

In [ ]:
# >,<
arr1 < arr2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
# ==
arr1 == arr2 # ¡Cuidado! en este caso, los arrays son de integers, no de floats

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [ ]:
# >,<
arr1 < arr2

---