# Secciones de arrays

_Hasta ahora sabemos cómo crear arrays y realizar algunas operaciones con ellos, sin embargo, todavía no hemos aprendido cómo acceder a elementos concretos del array_

In [ ]:
import numpy as np

## Arrays de una dimensión

<div class="alert alert-warning" role="alert">
  Observemos que aqui usaremos el comando de <b> np.arange</b>, que crea un array de dimensión definida y lo llena con valores.
</div>

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Acceso a los datos

In [ ]:
# Accediendo al primer elemento
arr[4]

4

In [ ]:
# Accediendo al último
arr[-3]

7

### __¡Atención!__

<div class="alert alert-danger" role="alert">
NumPy devuelve <b>__vistas__ </b> de la sección que le pidamos, no <b>__copias__ </b>. Esto quiere decir que debemos prestar mucha atención a este comportamiento:
</div>

In [ ]:
arr_a = np.arange(10)
arr_b = arr_a
print(arr_a, arr_b)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_b[0] = 2
print(arr_a, arr_b)

[2 1 2 3 4 5 6 7 8 9] [2 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_c = arr_a.copy()
print(arr_a, arr_c)

[2 1 2 3 4 5 6 7 8 9] [2 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_c[0] = 0
print(arr_a, arr_c)

[2 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(10)
vec = arr[5:]

print(arr)
print(vec)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [ ]:
print(vec[2])
vec[2] = 21
print(vec, arr)

7
[ 5  6 21  8  9] [ 0  1  2  3  4  5  6 21  8  9]


In [ ]:
arr[5] = 999

print(arr)
print(vec)

[  0   1   2   3   4 999   6  21   8   9]
[999   6  21   8   9]


Lo mismo ocurre al revés:

In [ ]:
arr = np.arange(10)
vec = arr[5:].copy()

print(arr)
print(vec)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [ ]:
vec[-1] = 999

print(arr)
print(vec)

[0 1 2 3 4 5 6 7 8 9]
[  5   6   7   8 999]


`vec` apunta a las direcciones de memoria donde están guardados los elementos del array `arr` que hemos seleccionado, no copia sus valores, a menos que explícitamente hagamos:

In [ ]:
arr = np.arange(10)
vec = arr[:6].copy()

print(arr)
print(vec)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]


In [ ]:
arr[5] = 999

print(arr)
print(vec)

[  0   1   2   3   4 999   6   7   8   9]
[0 1 2 3 4 5]


## Arrays de dos dimensiones

### Método _reshape()_

Este comando nos permite cambiar las dimensiones de un arreglo, por ejemplo transformar un vector en matriz, sin perder su contenido.

In [ ]:
# En este caso, primero crearemos un vector de longitud 9 y luego le daremos forma de una matriz 3x3
arr = np.arange(9).reshape([3, 3])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Aqui accedemos al elemento [0, 1] de la matriz, recordar que Python indexa desde cero.

In [ ]:
arr[0,1]

1

Aqui accedemos al elemento [0, -1] de la matriz, rfecordar que Python indexa desde cero.

In [ ]:
arr[0, -1]

2

In [ ]:
arr[2, 2]

8

## Secciones de arrays

Hasta ahora hemos visto cómo acceder a elementos aislados del array, pero la potencia de NumPy está en poder acceder a secciones enteras.  
Para ello se usa la sintaxis `inicio:final:paso`: si alguno de estos valores no se pone toma un valor por defecto.  

Veamos ejemplos:

In [ ]:
M = np.arange(36, dtype=float).reshape(4, 9)
M

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23., 24., 25., 26.],
       [27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [ ]:
# De la segunda a la tercera fila, incluida
# Recordemos que Python no considera la última
M[1:3]

array([[ 9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23., 24., 25., 26.]])

In [ ]:
# Hasta la tercera fila sin incluir y de la segunda a la quinta columnas saltando dos
M[:2, 1:5:2]

array([[ 1.,  3.],
       [10., 12.]])

In [ ]:
M[1:2:1, 1:5:2]  # Veamos este caso

array([[10., 12.]])

##### Ejemplo

Definamos una matriz que represente un tablero de ajedrez, con 0 los casilleros negros y 1 con los blancos.

In [ ]:
tablero = np.zeros([8, 8], dtype=int)

tablero[0::2, 1::2] = 1 # [0::2] corresponde a las filas y [1::2] a las columnas
# Esto significa que [0::2] comienza con la fila 0 y avanza de a saltos de 2
# Esto significa que [1::2] comienza con la columna 1 y avanza de a saltos de 2
tablero[1::2, 0::2] = 1
# Esta sentencia hace algo similar a lo anterior

tablero

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])