# Álgebra Lineal con NumPy

_Una vez que hemos visto el manejo básico de arrays en Python con NumPy, es hora de pasar a operaciones más interesantes como son las propias del Álgebra Lineal._

_Los productos escalares y las inversiones de matrices están por todas partes en los programas científicos, así que vamos a estudiar cómo se realizan en Python._

## Álgebra lineal

Como sabemos, las operaciones del álgebra lineal aparecen con mucha frecuencia a la hora de resolver sistemas de ecuaciones en derivadas parciales y en general al linealizar problemas de todo tipo, y suele ser necesario resolver sistemas con un número enorme de ecuaciones e incógnitas.  

Gracias a los arrays de NumPy podemos abordar este tipo de cálculos en Python, ya que todas las funciones están escritas en C o Fortran y tenemos la opción de usar bibliotecas optimizadas al límite.

El paquete de álgebra lineal en NumPy se llama `linalg`, así que importando NumPy con la convención habitual podemos acceder a él escribiendo `np.linalg`. Si imprimimos la ayuda del paquete vemos que tenemos funciones para:

* Funciones básicas (norma de un vector, inversa de una matriz, determinante, traza)
* Resolución de sistemas
* Autovalores y autovectores
* Descomposiciones matriciales (QR, SVD)
* Pseudoinversas

In [ ]:
import numpy as np

In [ ]:
from numpy.linalg import norm, det
#help(norm)

In [ ]:
# help(np.linalg)

Recordemos que si queremos usar una función de un paquete pero no queremos escribir la "ruta" completa cada vez, podemos usar la sintaxis `from package import func`:

El producto matricial usual (no el que se hace elemento a elemento, sino el del álgebra lineal) se calcula con la misma función que el producto matriz-vector y el producto escalar vector-vector: con la función `dot`, que **no** está en el paquete `linalg` sino directamente en `numpy` y no hace falta importarlo.

In [ ]:
c = np.array([[ 1, 0, 0],
              [ 1, 1, 0],
              [ 1, 1, 1]] )

print(norm(c, axis=-2))
print(norm(c, axis=1))
print(norm(c, axis=0))
print(norm(c, axis=-1))
print(norm(c))

[1.732 1.414 1.   ]
[1.    1.414 1.732]
[1.732 1.414 1.   ]
[1.    1.414 1.732]
2.449489742783178


In [ ]:
np.dot

<function numpy.dot>

Una consideración importante a tener en cuenta es que en NumPy no hace falta ser estricto a la hora de manejar vectores como si fueran matrices columna, siempre que la operación sea consistente.

Un vector es una matriz con una sola dimensión: por eso si calculamos su traspuesta no funciona.

In [ ]:
M = np.array([
    [1, 2],
    [3, 4]
])
v = np.array([1, -1])
print(v)

[ 1 -1]


#### Así calculamos la Transpuesta

In [ ]:
print(v.T)


[ 1 -1]


In [ ]:
M.T

array([[1, 3],
       [2, 4]])

In [ ]:
M

array([[1, 2],
       [3, 4]])

In [ ]:
v

array([ 1, -1])

In [ ]:
u = np.dot(M, v)
u

array([-1, -1])

In [ ]:
u = np.dot(v, M)
u

array([-2, -2])

#### Aclaremos este producto

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
np.dot(a,b)

array([[37, 40],
       [85, 92]])

Teniendo en cuenta que el producto punto se calcula como:

`[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]`

### Los flotantes no se pueden comparar por igualdad

Para hacer comparaciones entre arrays de punto flotante se pueden usar las funciones `np.allclose` y `np.isclose`.

La primera comprueba si todos los elementos de los arrays son iguales dentro de una tolerancia, y la segunda compara elemento a elemento y devuelve un array de valores `True` y `False`.

In [ ]:
u, v

(array([-2, -2]), array([ 1, -1]))

In [ ]:
np.allclose(u, v)

False

In [ ]:
np.isclose(0.0, 1e-8, atol=1e-10)

False

In [ ]:
np.allclose([1e10,1e-7], [1.00001e10,1e-8])

False

In [ ]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

In [ ]:
abs(a-b)< 1e-8

__En la versión 3.5 de Python se incorporó un nuevo operador `@` para poder hacer multiplicaciones de matrices de una forma más legible__

In [ ]:
print(M)
print(v)
u = M @ v
u

[[1 2]
 [3 4]]
[ 1 -1]


array([-1, -1])

Esto es, en modo matemático
$$
\left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array} \right)
%
\left( \begin{array}{cc}
 1 \\
-1
\end{array} \right)
%
=
\left( \begin{array}{cc}
-1 \\
-1
%
\end{array} \right)
$$

In [ ]:
mat = np.array([[1, 5, 8, 5],
                [0, 6, 4, 2],
                [9, 3, 1, 6]])

vec1 = np.array([5, 6, 2])

vec1 @ mat

array([23, 67, 66, 49])

Si quieres saber más, puedes leer [este artículo](http://pybonacci.org/2016/02/22/el-producto-de-matrices-y-el-nuevo-operador/) en Pybonacci escrito por _Álex Sáez_.

##### Ejemplos

_____________________________
1- Hallar el producto de estas dos matrices y su determinante:

$$\begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 1 \\ -1 & 0 & 1 \end{pmatrix} \begin{pmatrix} 2 & 3 & -1 \\ 0 & -2 & 1 \\ 0 & 0 & 3 \end{pmatrix}$$

In [ ]:
from numpy.linalg import det

In [ ]:
A = np.array([
    [1, 0, 0],
    [2, 1, 1],
    [-1, 0, 1]
])
B = np.array([
    [2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]
])
print(A)
print(B)

[[ 1  0  0]
 [ 2  1  1]
 [-1  0  1]]
[[ 2  3 -1]
 [ 0 -2  1]
 [ 0  0  3]]


In [ ]:
C = A @ B
C

array([[ 2,  3, -1],
       [ 4,  4,  2],
       [-2, -3,  4]])

In [ ]:
det(C)

-12.0

_____________________________________
2- Resolver el siguiente sistema:

$$ \begin{pmatrix} 2 & 0 & 0 \\ -1 & 1 & 0 \\ 3 & 2 & -1 \end{pmatrix} \begin{pmatrix} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} -1 \\ 3 \\ 0 \end{pmatrix} $$

In [ ]:
M = (np.array([[2, 0, 0],
                        [-1, 1, 0],
                        [3, 2, -1]])
     @
        np.array([[1, 1, 1],
                        [0, 1, 2],
                        [0, 0, 1]]))
M

array([[ 2,  2,  2],
       [-1,  0,  1],
       [ 3,  5,  6]])

In [ ]:
R = np.array([-1, 3, 0])

In [ ]:
x = np.linalg.solve(M, R)
x

array([ 0.5, -4.5,  3.5])

In [ ]:
T = M @ x
T

array([-1.,  3.,  0.])

In [ ]:
np.allclose(M @ x, np.array([-1, 3, 0]))

True

____________________________
3- Hallar la inversa de la matriz $H$ y comprobar que $H H^{-1} = I$ (recuerda la función `np.eye`)

In [ ]:
H = np.arange(4).reshape((2, 2))
print(H)
print('--------')
np.random.shuffle(H)
print(H)

[[0 1]
 [2 3]]
--------
[[2 3]
 [0 1]]


In [ ]:
Hinv = np.linalg.inv(H)
Hinv

array([[ 0.5, -1.5],
       [ 0. ,  1. ]])

In [ ]:
np.linalg.det(H)

2.0

In [ ]:
print(np.dot(Hinv, H))

[[1. 0.]
 [0. 1.]]


In [ ]:
print(Hinv @ H)

[[1. 0.]
 [0. 1.]]


In [ ]:
np.isclose(np.dot(Hinv, H), np.eye(2))

array([[ True,  True],
       [ True,  True]])

In [ ]:
np.set_printoptions(precision=6)
print(np.dot(Hinv/3.0, H/3.0))

[[0.111111 0.      ]
 [0.       0.111111]]


_______________________________________
4- Comprobar el número de condición de la matriz $H$.  
El número de condición de x se define como la norma de x por el norma de la inversa de x [1] ; la norma puede ser la norma L2 habitual (raíz de la suma de los cuadrados) o una de varias otras normas de matriz.

In [ ]:
np.linalg.cond(H)

6.8541019662496865

<div class="alert alert-warning">La matriz está bien condicionada.</div>